# Generated by Django 5.1 on 2024-10-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('pdf_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='summarizer.pdfupload')),
            ],
        ),
    ]
